services:
  n8n-main:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=DOMINIO.COM
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_EXECUTIONS_PROCESS=queue
      - N8N_QUEUE_REDIS_URL=redis://redis:6379
      - N8N_DB_TYPE=postgresdb
      - N8N_DB_POSTGRES_HOST=postgres
      - N8N_DB_POSTGRES_PORT=5432
      - N8N_DB_POSTGRES_DATABASE=${N8N_DB_POSTGRES_DATABASE}
      - N8N_DB_POSTGRES_USER=${N8N_DB_POSTGRES_USER}
      - N8N_DB_POSTGRES_PASSWORD=${N8N_DB_POSTGRES_PASSWORD}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - GENERIC_TIMEZONE=${TZ}
      - TZ=${TZ}
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - NODE_ENV=production
      - N8N_RUNNERS_ENABLED=true
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=90
      - EXECUTIONS_DATA_SAVE_ON_ERROR=all
      - EXECUTIONS_DATA_SAVE_ON_SUCCESS=all
      - EXECUTIONS_DATA_SAVE_ON_PROGRESS=all
      - EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS=all
      - EXECUTIONS_TIMEOUT=300
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - redis
      - postgres
    networks:
      - n8n-network


  n8n-worker:
    image: n8nio/n8n
    restart: always
    environment:
      - N8N_EXECUTIONS_PROCESS=queue
      - N8N_QUEUE_REDIS_URL=redis://redis:6379
      - N8N_DB_TYPE=postgresdb
      - N8N_DB_POSTGRES_HOST=postgres
      - N8N_DB_POSTGRES_PORT=5432
      - N8N_DB_POSTGRES_DATABASE=${N8N_DB_POSTGRES_DATABASE}
      - N8N_DB_POSTGRES_USER=${N8N_DB_POSTGRES_USER}
      - N8N_DB_POSTGRES_PASSWORD=${N8N_DB_POSTGRES_PASSWORD}
      - NODE_ENV=production
      - N8N_RUNNERS_ENABLED=true
      - TZ=${TZ}
      - GENERIC_TIMEZONE=${TZ}
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=90
      - EXECUTIONS_DATA_SAVE_ON_ERROR=all
      - EXECUTIONS_DATA_SAVE_ON_SUCCESS=all
      - EXECUTIONS_DATA_SAVE_ON_PROGRESS=all
      - EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS=all
      - EXECUTIONS_TIMEOUT=300
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - redis
      - postgres
    networks:
      - n8n-network
    deploy:
      replicas: ${N8N_WORKER_REPLICAS:-2}


  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - n8n-network

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=${N8N_DB_POSTGRES_DATABASE}
      - POSTGRES_USER=${N8N_DB_POSTGRES_USER}
      - POSTGRES_PASSWORD=${N8N_DB_POSTGRES_PASSWORD}
      - TZ=${TZ}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - n8n-network

volumes:
  n8n_data:
  redis_data:
  postgres_data:

networks:
  n8n-network:
    driver: bridge
